# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "955895a982d9e495af60ecf5e4f0d9c1"
application_url = "https://spraay-shopify-production.up.railway.app"
embedded = true
name = "Spraay"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://spraay-shopify-production.up.railway.app/auth/callback",
  "https://spraay-shopify-production.up.railway.app/auth/shopify/callback",
  "https://spraay-shopify-production.up.railway.app/api/auth/callback",
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
